### ISSUE TITLE
Cesium Animation

### ISSUE THREAD

**Issue by amar0k** [satellogic/grafana-3d-globe-panel#14]
I am trying to enable animation in the SceneMode options from module.js but get the following error when rendering.

TypeError: Cannot read property 'update' of undefined. Along with a bunch of console errors.

Is there anymore work being done on this or am i on my own? Any advice would be greatly appreciated.

Thanks.

**Comment by peregrinogris** [comment]
Hi @ASimpson87, can you tell us some more about your problem so we can help? These would be helpful:

* Grafana version.
* How did you install the plugin. (Did you build it?).
* Browser/OS you're using.

**Comment by amar0k** [comment]
Thanks for the reply ,

Grafana 4.2
I built it with npm build and just ran it from my grafana source project 
And running chrome on win7

**Comment by amar0k** [comment]
Is the cesium animation container working on this plugin yet or is it something that needs to be added ? I'm happy to contribute.

**Comment by peregrinogris** [comment]
Cool, helping hands are welcome! Right now I can't remember exactly why we turned the animation off, but give me some time to get my head around the code again and will get back to you.

Now you mention Grafana 4.2, I should test this plugin there, it was only tested in Grafana 3 and 4.

**Comment by amar0k** [comment]
Ok thanks for that , I'll start looking into it as well .. if you have any
ideas or find something let me know and see what we come up with.

Thanks again.
