### ISSUE TITLE
Cannot get / (Ubuntu)

### ISSUE THREAD

**Issue by tomek1978** [satellogic/grafana-3d-globe-panel#15]
Hi,

It looks like everything works, but it does not work :)

I'm trying to set up plugin on Grafana 5.0.4 with Nodejs 8.11.1 (ubuntu 16LTS)  and it seems that poor man's server works "properly" but...
1) node server.js give information about 3333
2) chromium http://localhost:3333 informs Cannot get /
3) @ grafana show information about 404

I admit that js is new for me.

Any suggestions?

regards
Tomek

**Comment by gilgamezh** [comment]
Hello! 

You have to serve a CZML. 

You can use it to test --> https://github.com/satellogic/grafana-3d-globe-panel/blob/master/server/server.js
